In [1]:
import os
import pprint
import tempfile
import pandas

In [2]:
import numpy as np
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_recommenders as tfrs

In [4]:
ratings = tfds.load("movielens/100k-ratings", split="train")

In [11]:
ratings = ratings.map(lambda x: {
    "movie_title": x["movie_title"],
    "user_id": x["user_id"],
})

In [12]:
for element in ratings: 
    print(element)
    break

{'movie_title': <tf.Tensor: shape=(), dtype=string, numpy=b"One Flew Over the Cuckoo's Nest (1975)">, 'user_id': <tf.Tensor: shape=(), dtype=string, numpy=b'138'>}


In [5]:
type(ratings)

tensorflow.python.data.ops.dataset_ops.PrefetchDataset

In [6]:
df = tfds.as_dataframe(ratings.take(10))

In [7]:
df.head()

bucketized_user_age movie_genres movie_id  \
0                 45.0          [7]   b'357'   
1                 25.0      [4, 14]   b'709'   
2                 18.0          [4]   b'412'   
3                 50.0       [5, 7]    b'56'   
4                 50.0     [10, 16]   b'895'   

                                 movie_title  raw_user_age  timestamp  \
0  b"One Flew Over the Cuckoo's Nest (1975)"          46.0  879024327   
1                b'Strictly Ballroom (1992)'          32.0  875654590   
2             b'Very Brady Sequel, A (1996)'          24.0  882075110   
3                     b'Pulp Fiction (1994)'          50.0  883326919   
4                         b'Scream 2 (1997)'          55.0  891409199   

   user_gender user_id  user_occupation_label user_occupation_text  \
0         True  b'138'                      4            b'doctor'   
1         True   b'92'                      5     b'entertainment'   
2         True  b'301'                     17           b'student'   
3         True   b'60'                      4        b'healthcare'   
4         True  b'197'                     18        b'technician'   

   user_rating user_zip_code  
0          4.0      b'53211'  
1          2.0      b'80525'  
2          4.0      b'55439'  
3          4.0      b'06472'  
4          3.0      b'75094'

In [8]:
movies = tfds.load("movielens/100k-movies", split="train")

Dl Completed...: 0 url [00:00, ? url/s]
Dl Size...: 0 MiB [00:00, ? MiB/s]

Dl Completed...:   0%|                                                                         | 0/1 [00:00<?, ? url/s]
Dl Size...: 0 MiB [00:00, ? MiB/s]

Dl Completed...: 100%|████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 166.60 url/s]
Dl Size...: 0 MiB [00:00, ? MiB/s]

Dl Size...:   0%|                                                                        | 0/4924029 [00:00<?, ? MiB/s]

Dl Size...: 100%|███████████████████████████████████████████████████| 4924029/4924029 [00:00<00:00, 492426850.36 MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]
Generating splits...:   0%|                                                                 | 0/1 [00:00<?, ? splits/s]
Generating train examples...: 0 examples [00:00, ? examples/s]
Generating train examples...: 1431 examples [00:00, 14236.63 examples/s]
                                                                

Dataset movielens downloaded and prepared to C:\Users\Bluecat\tensorflow_datasets\movielens\100k-movies\0.1.1. Subsequent calls will reuse this data.


In [9]:
movies = movies.map(lambda x: x["movie_title"])

In [10]:
for element in movies: 
    print(element)
    break

tf.Tensor(b'You So Crazy (1994)', shape=(), dtype=string)


In [12]:
for element in movies.batch(32):
    print(element)
    break

tf.Tensor(
[b'You So Crazy (1994)' b'Love Is All There Is (1996)'
 b'Fly Away Home (1996)' b'In the Line of Duty 2 (1987)'
 b'Niagara, Niagara (1997)' b"Young Poisoner's Handbook, The (1995)"
 b'Age of Innocence, The (1993)' b'Flirt (1995)' b'Frisk (1995)'
 b'unknown' b'Girls Town (1996)' b'Stonewall (1995)'
 b'African Queen, The (1951)' b'Bloody Child, The (1996)'
 b'Executive Decision (1996)' b'Batman Returns (1992)'
 b'Canadian Bacon (1994)' b'FairyTale: A True Story (1997)'
 b'Body Snatcher, The (1945)' b'Sabrina (1954)' b'Sphere (1998)'
 b'Magic Hour, The (1998)' b'Raise the Red Lantern (1991)'
 b'Homeward Bound II: Lost in San Francisco (1996)'
 b'Grosse Pointe Blank (1997)' b"Smilla's Sense of Snow (1997)"
 b'Princess Caraboo (1994)' b'Wings of Desire (1987)'
 b'Collectionneuse, La (1967)'
 b'To Wong Foo, Thanks for Everything! Julie Newmar (1995)'
 b'Lassie (1994)' b'Shadows (Cienie) (1988)'], shape=(32,), dtype=string)
